### ISSUE TITLE
Default input search provider is not working

### ISSUE THREAD

**Issue by yalikebaz** [lalitmee/browse.nvim#7]
Regarding customizing the input search provider, the docs say the default is google, however if you don't set a default my searches were taking me to 'nil.com'... so I had to set my provider to google manually. This suggests that the default is not google automatically.

**Comment by lalitmee** [comment]
When I am trying it in my config without setting anything, its working and opening the urls with `google.com`. Can you please check by uninstalling and installing again?

Can you also provide the config, so that we can see how you are applying it? It should be the first thing to set.

Not sure what can be the problem.

**Comment by lalitmee** [comment]
@ShaySS , any update?

**Comment by lalitmee** [comment]
closing this in favour of #8
